name: "Build builder"
description: "Builds the Docker builder image using GHA cache"

outputs:
  builder-name:
    description: "Name of the buildx builder"
    value: ${{ steps.setup-buildx.outputs.name }}

runs:
  using: "composite"
  steps:
    - id: setup-buildx
      uses: docker/setup-buildx-action@v2
    - name: Build builder
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        tags: wdm-shoppingcart-builder:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max