services:
  mongo_order:
    image: mongo:4.4
    container_name: mongo_order
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: LoFiBeats
    volumes:
      - "./dev/mongo/data/order:/data/db"
      - "./dev/mongo/order/init.js:/docker-entrypoint-initdb.d/init.js"
  mongo_payment:
    image: mongo:4.4
    container_name: mongo_payment
    ports:
      - "127.0.0.1:27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: LoFiBeats
    volumes:
      - "./dev/mongo/data/payment:/data/db"
      - "./dev/mongo/payment/init.js:/docker-entrypoint-initdb.d/init.js"

  mongo_stock:
    image: mongo:4.4
    container_name: mongo_stock
    ports:
      - "127.0.0.1:27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: LoFiBeats
    volumes:
      - "./dev/mongo/data/stock:/data/db"
      - "./dev/mongo/stock/init.js:/docker-entrypoint-initdb.d/init.js"

  order_service:
    image: order_service:0
    container_name: order_service
    build:
      context: ./docker/order-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 50001:50000

  payment_service:
    image: payment_service:0
    container_name: payment_service
    build:
      context: ./docker/payment-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 50002:50001

  stock_service:
    image: stock_service:0
    container_name: stock_service
    build:
      context: ./docker/stock-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 50003:50002

  api_gateway:
    image: api_gateway:0
    container_name: api_gateway
    build:
      context: ./docker/api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 50003:50002
