services:
  mongo:
    image: mongo:4.4
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: LoFiBeats
    volumes:
      - "mongo-data:/data/db"
      - "./dev/mongo/init.js:/docker-entrypoint-initdb.d/init.js"

volumes:
  mongo-data: {}