version: '3'

output: prefixed

includes:
  dev: ./dev
  dist: ./dist

env:
  # Enable buildkit for proper multistage Dockerfile builds
  # (skipping stages, which are not needed for the target)
  DOCKER_BUILDKIT: 1
  BUILDER_IMAGE: shopping-cart-builder

tasks:
  default:
    - task: docker:run
  prepare:
    - task: vendor
    - task: generate:protobuf
  vendor:
    cmds:
      - go mod vendor
    sources:
      - go.mod
      - go.sum
    generates:
      - vendor/modules.txt
  generate:protobuf:
    cmds:
      - go generate -x shopping-cart/api/proto/...
    sources:
      - api/proto/**/*.proto
    generates:
      - api/proto/**/*.pb.go
  vet:
    deps: [prepare]
    cmds: ["go vet ./..."]
  fmt:
    cmds: ["go fmt ./..."]
  build:
    - task: api_gateway:build
    - task: stock_service:build
    - task: payment_service:build
    - task: order_service:build
  build_docker:
    - task: api_gateway:build_docker
    - task: stock_service:build_docker
    - task: payment_service:build_docker
    - task: order_service:build_docker
  ########## API Gateway ###############################################################################################
  api_gateway:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/api-gateway {{.CLI_ARGS}}"]
  api_gateway:build:
    deps: [prepare]
    cmds: ["go build -o out/ shopping-cart/cmd/api-gateway"]
  api_gateway:build_docker: docker build --target api-gateway -t shopping-cart/api-gateway .
  ########## Stock Service #############################################################################################
  stock_service:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/stock-service {{.CLI_ARGS}}"]
  stock_service:build:
    deps: [prepare]
    cmds: ["go build -o out/ shopping-cart/cmd/stock-service"]
  stock_service:build_docker: docker build --target stock-service -t shopping-cart/stock-service .
  ########## Payment Service ###########################################################################################
  payment_service:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/payment-service {{.CLI_ARGS}}"]
  payment_service:build:
    deps: [prepare]
    cmds: ["go build -o out/ shopping-cart/cmd/payment-service"]
  payment_service:build_docker: docker build --target payment-service -t shopping-cart/payment-service .
  ########## Order Service #############################################################################################
  order_service:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/order-service {{.CLI_ARGS}}"]
  order_service:build:
    deps: [prepare]
    cmds: ["go build -o out/ shopping-cart/cmd/order-service"]
  order_service:build_docker: docker build --target order-service -t shopping-cart/order-service .
  ########## Cleanup ###################################################################################################
  clean:protobuf: find api/proto -type f -name "*.pb.go" -delete
  clean:containers: CONTAINERS="$(docker ps --format \'\{\{.Names\}\}\' | grep 'shoppingcart')"; CONTAINERS=${CONTAINERS//\'}; echo -e "Containers found :\n${CONTAINERS}"; if [[ -z "$CONTAINERS" ]]; then echo "No shopping cart containers were found"; else docker rm ${CONTAINERS}; fi
  clean:images: IMGS="$(docker images --format \'\{\{.Tag\}\}\' | grep 'shoppingcart')"; IMGS=${IMGS//\'}; echo -e "Images found :\n${IMGS}"; if [[ -z "$IMGS" ]]; then echo "No shopping cart images were found"; else docker rmi -f $IMGS; fi
  clean:
    - task: clean:protobuf
    - task: clean:containers
    - task: clean:images
    - rm -rf out
    - rm -rf vendor
  ########## Docker Builder ###########################################################################################
  docker:build_builder: docker build --target builder -t {{.BUILDER_IMAGE}} .
  docker:run:
    deps: [docker:build_builder]
    interactive: true
    vars:
      UID:
        sh: id -u
      GID:
        sh: id -g
      PWD:
        sh: pwd
    cmds:
      - >
        docker run -it
        --network host
        --user {{.UID}}:{{.GID}}
        --workdir /project
        --env GOCACHE=/tmp/gocache
        --volume {{.PWD}}:/project
        {{.BUILDER_IMAGE}}
        {{.CLI_ARGS}}
  ########## Test ######################################################################################################
  test:
    - go test -v -coverprofile cover.out ./...
    - go tool cover -html=cover.out -o cover.html
