version: '3'

vars:
  BUILDER_IMAGE: wdm-shoppingcart-builder

tasks:
  # Preparation
  dev_prepare:
    - task: vendor
    - task: generate_protobuf
  vendor:
    cmds:
      - go mod vendor
    sources:
      - go.mod
      - go.sum
    generates:
      - vendor/modules.txt
  generate_protobuf:
    cmds:
      - go generate -x shopping-cart/api/proto/...
    sources:
      - api/proto/**/*.proto
    generates:
      - api/proto/**/*.pb.go
  # Run
  run_stock_service:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/stock-service {{.CLI_ARGS}}"]
  run_order_service:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/order-service {{.CLI_ARGS}}"]
  run_payment_service:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/payment-service {{.CLI_ARGS}}"]
  run_api_gateway:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/api-gateway {{.CLI_ARGS}}"]
  # Build
  build:
    - task: build_stock_service
    - task: build_order_service
    - task: build_payment_service
    - task: build_api_gateway
  build_stock_service:
    deps: [dev_prepare]
    vars:
      OUTPUT: dist/stock-service
    cmds:
      - go build -o dist/ shopping-cart/cmd/stock-service
    generates:
      - dist
  build_order_service:
    deps: [dev_prepare]
    cmds:
      - go build -o dist/ shopping-cart/cmd/order-service
    generates:
      - dist
  build_payment_service:
    deps: [dev_prepare]
    cmds:
      - go build -o dist/ shopping-cart/cmd/payment-service
    generates:
      - dist
  build_api_gateway:
    deps: [dev_prepare]
    cmds:
      - go build -o dist/ shopping-cart/cmd/api-gateway
    generates:
      - dist
  # Cleanup
  clean_protobuf: find api/proto -type f -name "*.pb.go" -delete
  clean_dist: rm -rf dist
  clean:
    - task: clean_protobuf
    - task: clean_dist
    - rm -rf vendor
  # Docker
  docker_build:
    cmds:
      - docker build -t {{.BUILDER_IMAGE}} -f build/builder/Dockerfile .
    sources:
      - build/builder/**
    status:
      - docker inspect {{.BUILDER_IMAGE}}
  # TODO: two versions of the docker task, for Windows and UNIX
  docker:
    vars:
      UID:
        sh: id -u
      GID:
        sh: id -g
      PWD:
        sh: pwd
    deps: [docker_build]
    cmds:
      - >
        docker run -it
        --network host
        --user {{.UID}}:{{.GID}}
        --workdir /project
        --env GOCACHE=/tmp/gocache
        --volume {{.PWD}}:/project
        {{.BUILDER_IMAGE}}
        {{.CLI_ARGS}}


