version: '3'

output: prefixed

includes:
  docker: ./docker
  dev: ./dev

tasks:
  default:
    - task: docker:run
  prepare:
    - task: vendor
    - task: generate:protobuf
  vendor:
    cmds:
      - go mod vendor
    sources:
      - go.mod
      - go.sum
    generates:
      - vendor/modules.txt
  generate:protobuf:
    cmds:
      - go generate -x shopping-cart/api/proto/...
    sources:
      - api/proto/**/*.proto
    generates:
      - api/proto/**/*.pb.go
  build:
    - task: api_gateway:build
    - task: stock_service:build
    - task: payment_service:build
    - task: order_service:build
  build_docker:
    - task: api_gateway:build_docker
    - task: stock_service:build_docker
    - task: payment_service:build_docker
    - task: order_service:build_docker
  ########## API Gateway ###############################################################################################
  api_gateway:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/api-gateway {{.CLI_ARGS}}"]
  api_gateway:build:
    deps: [prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/api-gateway"]
  api_gateway:build_docker:
    deps: [docker:build_builder]
    cmds: ["docker build -t wdm-shoppingcart/api-gateway -f docker/api-gateway/Dockerfile ."]
  ########## Stock Service #############################################################################################
  stock_service:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/stock-service {{.CLI_ARGS}}"]
  stock_service:build:
    deps: [prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/stock-service"]
  stock_service:build_docker:
    deps: [docker:build_builder]
    cmds: ["docker build -t wdm-shoppingcart/stock-service -f docker/stock-service/Dockerfile ."]
  ########## Payment Service ###########################################################################################
  payment_service:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/payment-service {{.CLI_ARGS}}"]
  payment_service:build:
    deps: [prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/payment-service"]
  payment_service:build_docker:
    deps: [docker:build_builder]
    cmds: ["docker build -t wdm-shoppingcart/payment-service -f docker/payment-service/Dockerfile ."]
  ########## Order Service #############################################################################################
  order_service:run:
    deps: [prepare]
    cmds: ["go run shopping-cart/cmd/order-service {{.CLI_ARGS}}"]
  order_service:build:
    deps: [prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/order-service"]
  order_service:build_docker:
    deps: [docker:build_builder]
    cmds: ["docker build -t wdm-shoppingcart/order-service -f docker/order-service/Dockerfile ."]
  ########## Test ######################################################################################################
  test: go test ./...
  ########## Cleanup ###################################################################################################
  clean:protobuf: find api/proto -type f -name "*.pb.go" -delete
  clean:dist: rm -rf dist
  clean:containers: CONTAINERS="$(docker ps --format \'\{\{.Names\}\}\' | grep 'shoppingcart')"; CONTAINERS=${CONTAINERS//\'}; echo -e "Containers found :\n${CONTAINERS}"; if [[ -z "$CONTAINERS" ]]; then echo "No shopping cart containers were found"; else docker rm ${CONTAINERS}; fi
  clean:images: IMGS="$(docker images --format \'\{\{.Tag\}\}\' | grep 'shoppingcart')"; IMGS=${IMGS//\'}; echo -e "Images found :\n${IMGS}"; if [[ -z "$IMGS" ]]; then echo "No shopping cart images were found"; else docker rmi -f $IMGS; fi
  clean:
    - task: clean:protobuf
    - task: clean:containers
    - task: clean:images
    - task: clean:dist
    - rm -rf vendor
