version: '3'

output: prefixed

includes:
  docker: ./build/builder/Taskfile.yaml

tasks:
  default:
    - task: docker:run
  dev_prepare:
    - task: vendor
    - task: generate:protobuf
  vendor:
    cmds:
      - go mod vendor
    sources:
      - go.mod
      - go.sum
    generates:
      - vendor/modules.txt
  generate:protobuf:
    cmds:
      - go generate -x shopping-cart/api/proto/...
    sources:
      - api/proto/**/*.proto
    generates:
      - api/proto/**/*.pb.go
  build:
    - task: api_gateway:build
    - task: stock_service:build
    - task: payment_service:build
    - task: order_service:build
  ########## API Gateway ###############################################################################################
  api_gateway:run:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/api-gateway {{.CLI_ARGS}}"]
  api_gateway:build:
    deps: [dev_prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/api-gateway"]
  ########## Stock Service #############################################################################################
  stock_service:run:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/stock-service {{.CLI_ARGS}}"]
  stock_service:build:
    deps: [dev_prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/stock-service"]
  ########## Payment Service ###########################################################################################
  payment_service:run:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/payment-service {{.CLI_ARGS}}"]
  payment_service:build:
    deps: [dev_prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/payment-service"]
  ########## Order Service #############################################################################################
  order_service:run:
    deps: [dev_prepare]
    cmds: ["go run shopping-cart/cmd/order-service {{.CLI_ARGS}}"]
  order_service:build:
    deps: [dev_prepare]
    cmds: ["go build -o dist/ shopping-cart/cmd/order-service"]
  ########## Cleanup ###################################################################################################
  clean:protobuf: find api/proto -type f -name "*.pb.go" -delete
  clean:dist: rm -rf dist
  clean:
    - task: clean:protobuf
    - task: clean:dist
    - rm -rf vendor