version: '3'

output: interleaved

env:
  COMPOSE_PROJECT_NAME: shopping-cart-dev
  COMPOSE_FILE: dev/docker-compose.yml

vars:
  DEV_COMPOSE: "docker compose --project-directory ."

tasks:
  compose: "{{.DEV_COMPOSE}} {{.CLI_ARGS}}"
  compose:up: "{{.DEV_COMPOSE}} up --build --detach {{.CLI_ARGS}}"
  compose:start: "{{.DEV_COMPOSE}} up {{.CLI_ARGS}}"
  compose:stop: "{{.DEV_COMPOSE}} stop {{.CLI_ARGS}}"
  compose:down: "{{.DEV_COMPOSE}} down --volumes {{.CLI_ARGS}}"
  compose:logs: "{{.DEV_COMPOSE}} logs -f {{.CLI_ARGS}}"