name: "Run in builder"
description: "Runs the command in the builder container"

inputs:
  command:
    description: "Command to run inside the builder container"
    required: true

runs:
  using: "composite"
  steps:
    - uses: addnab/docker-run-action@v3
      with:
        image: local.local/shopping-cart-builder:latest
        options: -w /project -v ${{ github.workspace }}:/project
        run: ${{ inputs.command }}