version: '3'

vars:
  BUILDER_IMAGE: wdm-shoppingcart-builder

tasks:
  build_builder:
    cmds:
      - docker build -t {{.BUILDER_IMAGE}} -f docker/Dockerfile .
  run:
    deps: [build_builder]
    interactive: true
    vars:
      UID:
        sh: id -u
      GID:
        sh: id -g
      PWD:
        sh: pwd
      SERVICE_NAME:
        sh: basename "$PWD"
    cmds:
      - >
        docker run -it
        --network host
        --user {{.UID}}:{{.GID}}
        --workdir /project
        --env GOCACHE=/tmp/gocache
        --volume {{.PWD}}:/project
        --rm
        --name {{.SERVICE_NAME}}
        {{.BUILDER_IMAGE}}
        {{.CLI_ARGS}}
  
