apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopping-cart.stockService.fullname" . }}
  labels:
    {{- include "shopping-cart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.stockService.autoscaling.enabled }}
  replicas: {{ .Values.stockService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "shopping-cart.stockService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.stockService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shopping-cart.stockService.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shopping-cart.stockService.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.stockService.podSecurityContext | nindent 8 }}
      containers:
        - name: stock-service
          securityContext:
            {{- toYaml .Values.stockService.securityContext | nindent 12 }}
          image: "{{ .Values.stockService.image.repository }}:{{ .Values.stockService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.stockService.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50002
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 50002
          readinessProbe:
            tcpSocket:
              port: 50002
          resources:
            {{- toYaml .Values.stockService.resources | nindent 12 }}
      {{- with .Values.stockService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stockService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stockService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
