{{- if .Values.paymentService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shopping-cart.paymentService.serviceAccountName" . }}
  labels:
    {{- include "shopping-cart.labels" . | nindent 4 }}
  {{- with .Values.paymentService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
