apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopping-cart.paymentService.fullname" . }}
  labels:
    {{- include "shopping-cart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.paymentService.service.type }}
  ports:
    - port: {{ .Values.paymentService.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "shopping-cart.paymentService.selectorLabels" . | nindent 4 }}
