apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopping-cart.orderService.configMap" . }}
  labels:
    {{- include "shopping-cart.labels" . | nindent 4 }}
data:
  config.yaml: |
    stock-service:
      address: {{ include "shopping-cart.stockService.serviceAddress" . }}
    payment-service:
      address: {{ include "shopping-cart.paymentService.serviceAddress" . }}