apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopping-cart.orderService.fullname" . }}
  labels:
    {{- include "shopping-cart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "shopping-cart.orderService.selectorLabels" . | nindent 4 }}
