name: Build

on: push

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build_api_gateway:
    name: Build API gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: true
          dockerfile: docker/api-gateway/Dockerfile
          image-name: ${{ env.IMAGE_NAME }}/api-gateway
  build_order_service:
    name: Build order service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: true
          dockerfile: docker/order-service/Dockerfile
          image-name: ${{ env.IMAGE_NAME }}/order-service
  build_payment_service:
    name: Build payment service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: true
          dockerfile: docker/payment-service/Dockerfile
          image-name: ${{ env.IMAGE_NAME }}/payment-service
  build_stock_service:
    name: Build stock service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: true
          dockerfile: docker/stock-service/Dockerfile
          image-name: ${{ env.IMAGE_NAME }}/stock-service