name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build_api_gateway:
    name: Build API gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: api-gateway
          image-name: ${{ env.IMAGE_NAME }}/api-gateway
  build_order_service:
    name: Build order service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: order-service
          image-name: ${{ env.IMAGE_NAME }}/order-service
  build_payment_service:
    name: Build payment service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: payment-service
          image-name: ${{ env.IMAGE_NAME }}/payment-service
  build_stock_service:
    name: Build stock service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/builder_build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: stock-service
          image-name: ${{ env.IMAGE_NAME }}/stock-service