name: Verify

on: push

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
      - name: Lint
        uses: ./.github/actions/builder_run
        with:
          command: task vet
      - name: Format
        uses: ./.github/actions/builder_run
        with:
          command: task fmt
      - name: Verify format
        run: git diff --exit-code
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
      - name: Test
        uses: ./.github/actions/builder_run
        with:
          command: task test